#!/usr/bin/env bash
# Usage: bash install_epstopdf

sudo apt update || true
sudo apt install -y wget
URL="https://tug.org/svn/texlive/trunk/Build/extra/epstopdf/epstopdf.pl?view=co"
sudo wget "$URL" -O /usr/bin/epstopdf
sudo chmod +x /usr/bin/epstopdf
which epstopdf
epstopdf --version
