#!/bin/bash
# Usage: bash install_flang

FLANG_DFT="$HOME/local/flang"

if [[ ! -d /home/runner/work/ ]] ; then
    printf "\nThe runner is not hosted by GitHub. Skip installation of p7zip and ncurses.\n"
    if [[ -d $FLANG_DFT && -f $FLANG_DFT/bin/flang && -f $FLANG_DFT/bin/flang ]] ;then
        echo "PATH=$PATH:$FLANG_DFT/bin" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FLANG_DFT/lib" >> "$GITHUB_ENV"
        printf "\nflang is already installed. Skip installation.\n"
        exit 0
    fi
else
    if [[ "$RUNNER_OS" == "Linux" ]] ; then
        sudo apt update && sudo apt install p7zip-full libncurses* # libncurses* needed for libtinfo.so
    elif [[ "$RUNNER_OS" == "macOS" ]] ; then
        brew install p7zip ncurses
    fi
fi

cd /tmp/ || exit 42

PI_MODEL_FILE="/sys/firmware/devicetree/base/model"
if [[ -f "$PI_MODEL_FILE" ]]  && grep -qi 'Raspberry Pi' < "$PI_MODEL_FILE" ; then  # Raspberry Pi
    FLANG_URL="https://www.dropbox.com/s/jqff6oyo2t103gl/flang.aarch64.7z"
elif [[ $(uname -s) == 'Darwin' ]] ; then  # macOS
    FLANG_URL="https://www.dropbox.com/s/04oxwzbhnodghh3/flang.macos_x86.7z"
else  # Linux
    FLANG_URL="https://www.dropbox.com/s/ic76m3dm61ztw5g/flang.x86_64.7z"
fi

FLANG_7Z="flang.7z"
wget "$FLANG_URL" -O "$FLANG_7Z"
7za x "$FLANG_7Z" -aoa  # -aoa: overwrite all existing files without prompt

# Set environment variable for subsequent steps
# N.B.: The following lines will not work if this script is invoked with sudo.
echo "PATH=$PATH:/tmp/flang/bin" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/flang/lib" >> "$GITHUB_ENV"
