#!/usr/bin/env bash
# Usage: bash install_llvm
# N.B.: VERSION_NUMBER is used only on Linux; on macOS, Homebrew will always install the latest
# version of LLVM as of 2026.
# The script will determine the version number based on the current date and the LLVM release
# schedule, which is updated every six months as of 2026, in March and September. The version number
# in September 2025 is 21.

set -euo pipefail

if [[ $(uname -s) == 'Darwin' ]] ; then  # macOS
    brew update || true
    # clang is included in llvm, but flang and lld are separate packages.
    brew install llvm flang lld  # The latest version will be installed, which is 21 in September 2025.
else  # Assume Linux

    # Install prerequisites.
    sudo apt update || true && sudo apt install -y curl gnupg

    # According to "LLVM Release Schedule" at https://llvm.org, we assume that the version is
    # updated every six months, in March and September. The version number in September 2025 is 21.
    CURRENT_YEAR=$(date +%Y)
    CURRENT_MONTH=$(date +%m)
    CURRENT_MONTH=${CURRENT_MONTH#0} # Remove leading zero if any
    echo "Current year: ${CURRENT_YEAR}, current month: ${CURRENT_MONTH}"
    if [[ ${CURRENT_MONTH} -ge 9 ]]; then
        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2025) * 2))
    elif [[ ${CURRENT_MONTH} -ge 3 ]]; then
        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2025) * 2 - 1))
    else
        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2026) * 2 ))
    fi
    echo "Using the version number ${VERSION_NUMBER} based on the current date."

    # Add the LLVM repository and the GPG key.
    # See https://apt.llvm.org/
    UBUNTU_CODENAME=$(lsb_release -sc 2>/dev/null || grep VERSION_CODENAME /etc/os-release | cut -d= -f2)
    curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
        | gpg --dearmor --yes \
        | sudo tee /usr/share/keyrings/apt.llvm.org.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/apt.llvm.org.gpg] https://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${VERSION_NUMBER} main" \
        | sudo tee /etc/apt/sources.list.d/llvm-toolchain-${VERSION_NUMBER}.list

    # Install the packages (clang is needed even if we use only flang).
    sudo apt update
    sudo apt install -y llvm-${VERSION_NUMBER} flang-${VERSION_NUMBER} clang-${VERSION_NUMBER}  lld-${VERSION_NUMBER}

    # Verify the installation
    for TOOL in flang clang lld; do
        type "${TOOL}-${VERSION_NUMBER}" > /dev/null 2>&1 || \
            { echo "${TOOL}-${VERSION_NUMBER} not found after the installation, which probably failed." >&2 ; exit 1; }
    done

    # Set up symlinks pointing to tool-${VERSION_NUMBER}
    for TOOL in flang clang lld; do
        BIN_DIR="/usr/local/bin"  # This usually comes before /usr/bin in PATH
        if [[ -f "${BIN_DIR}/${TOOL}" || -L "${BIN_DIR}/${TOOL}" ]]; then
            echo "${TOOL} already exists in ${BIN_DIR}:"
            ls -al "${BIN_DIR}/${TOOL}"
            echo "Backing ${TOOL} to ${TOOL}.bak"
            sudo mv "${BIN_DIR}/${TOOL}" "${BIN_DIR}/${TOOL}.bak"
        fi
        echo "Creating a symbolic link named ${TOOL} pointing to ${TOOL}-${VERSION_NUMBER} in ${BIN_DIR}."
        sudo ln -sf "$(command -v ${TOOL}-${VERSION_NUMBER})" "${BIN_DIR}/${TOOL}"
    done

fi

# Verify installation
for TOOL in flang clang lld; do
    type $TOOL > /dev/null 2>&1 || \
        { echo "$TOOL not found after the installation, which probably failed." >&2 ; exit 1; }
done

# Final messages
echo "LLVM installation completed."
for TOOL in flang clang lld; do
    echo -e "\nThe $TOOL version is:\n"
    "$TOOL" --version
    echo -e "\nThe path to $TOOL is:\n"
    command -v "$TOOL"
done
