#!/bin/bash
# Usage: bash install_flang

sudo apt install p7zip-full libncurses* # libncurses* needed for libtinfo.so

cd /tmp/ || exit 42

wget "https://www.dropbox.com/s/ic76m3dm61ztw5g/flang.x86_64.7z"
7za x flang.x86_64.7z

# Set environment variable for subsequent steps
# N.B.: The following lines will not work if this script is invoked with sudo.
echo "PATH=$PATH:/tmp/flang/bin" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/flang/lib" >> "$GITHUB_ENV"
