#!/bin/bash
# Usage: bash install_aocc

sudo apt update && sudo apt install p7zip-full libncurses* -y  # libncurses* needed for libtinfo.so

cd /tmp || exit 42

git clone https://github.com/zaikunzhang/resources

cd resources/ || exit 42

AOCC_7Z="aocc_flang.deb.7z.001"
7za x "$AOCC_7Z" -aoa  # -aoa: overwrite all existing files without prompt

sudo dpkg -i /tmp/aocc_flang.deb

# Run the script that sets the necessary environment variables and then damp them to $GITHUB_ENV
# so that they are available in subsequent steps.
if [[ -d /opt/AMD ]] ; then
    AOCCDIR="$(find /opt/AMD -maxdepth 1 -name "aocc-compiler*" -type d -print | sort | tail -n 1)"
    AOCC_ENVSH="$(find "$AOCCDIR" -name "*setenv*.sh" -type f)"
    #shellcheck disable=SC1090
    source "$AOCC_ENVSH"
else
    exit 1
fi
env | grep -i 'aocc\|AMD' >> "$GITHUB_ENV"
