#!/bin/bash
# Usage: bash install_aocc

cd /tmp || exit 42

wget "https://www.dropbox.com/s/5xxfpr0tx8kn0o1/aocc-compiler-4.0.0_1_amd64.deb" -O aocc.deb

sudo apt install /tmp/aocc.deb

# Run the AOCC script that sets the necessary environment variables and then damp them to
# $GITHUB_ENV so that they are available in subsequent steps.
if [[ -d /opt/AMD ]] ; then
    AOCCDIR="$(find /opt/AMD -maxdepth 1 -name "aocc-compiler*" -type d -print | sort | tail -n 1)"
    AOCC_ENVSH="$(find "$AOCCDIR" -name "*setenv*.sh" -type f)"
    #shellcheck disable=SC1090
    source "$AOCC_ENVSH"
fi
env | grep -i 'aocc\|AMD' >> "$GITHUB_ENV"
