#!/bin/bash
# Usage: bash install_sunf95

REPO_NAME=OracleDevStd
cd /tmp/ || exit 42
git clone https://github.com:zaikunzhang/"$REPO_NAME".git

cd "$REPO_NAME" || exit 42
ORACLE_7Z="OracleDevStd.7z.001"
7za x "$ORACLE_7Z" -aoa  # -aoa: overwrite all existing files without prompt

# Set environment variable for subsequent steps
echo "PATH=$PATH:/tmp/$REPO_NAME/OracleDevStd/bin" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=/tmp/$REPO_NAME/OracleDevStd/lib/compilers/sys/amd64:/tmp/$REPO_NAME/OracleDevStd/lib/compilers/sys/:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
