#!/bin/bash
# Usage: bash install_g95

REPO_NAME="flang"
G95DIR="/tmp/$REPO_NAME/g95/"

cd /tmp/ || exit 42
git clone https://github.com/zaikunzhang/"$REPO_NAME"
cd "$REPO_NAME" || exit 42
unzip g95.zip

# Make some links
CRT1="$(find /usr/ -type f -name "crt1.o*" -print -quit)"
CRTI="$(find /usr/ -type f -name "crti.o*" -print -quit)"
CRTN="$(find /usr/ -type f -name "crtn.o*" -print -quit)"
ln -s "$CRT1" "$G95DIR/lib/gcc-lib/x86_64-unknown-linux-gnu/4.0.3/"
ln -s "$CRTI" "$G95DIR/lib/gcc-lib/x86_64-unknown-linux-gnu/4.0.3/"
ln -s "$CRTN" "$G95DIR/lib/gcc-lib/x86_64-unknown-linux-gnu/4.0.3/"

# Set environment variable for subsequent steps
echo "PATH=$PATH:/tmp/resources/g95/bin:/tmp/resources/g95/lib/gcc-lib/x86_64-unknown-linux-gnu/4.0.3" >> "$GITHUB_ENV"
