#!/usr/bin/env bash
# This script installs miscellaneous libraries for GitHub Actions on ***hosted runners***.
#
# Usage: bash mist_setup

# Exit if the script is not executed during a GitHub Actions workflow on a GitHub-hosted runner.
# For GITHUB_ACTIONS and RUNNER_ENVIRONMENT variables, see:
# https://docs.github.com/en/actions/reference/workflows-and-actions/variables
 if [[ "$GITHUB_ACTIONS" != "true" || "$RUNNER_ENVIRONMENT" != "github-hosted" ]]; then
    printf "\nThis is not a GitHub Actions workflow on a GitHub-hosted runner. Nothing will be done.\n"
    exit 0
fi

if [[ "$RUNNER_OS" == "Linux" ]] ; then
    sudo apt update
    sudo apt install -y gdb make cmake ninja-build
    gdb --version
    make --version
    cmake --version
    ninja --version
    # The following packages are removed by the `large-packages` section of free-disk-space@v1.3.1.
    # Without x11-xkb-utils, MATLAB R2025a when running `plot` crashes with an internal error:
    # "Assertion: This application failed to start because no Qt platform plugin could be initialized".
    # This is why the script should be called AFTER free-disk-space.
    # See https://github.com/zequipe/test_matlab/actions/workflows/qt.yml
    # Without libgl1, MATLAB R2025a get stuck when profiling PRIMA.
    sudo apt install -y x11-xkb-utils libgl1
elif [[ "$RUNNER_OS" == "macOS" ]] ; then
    brew install coreutils make cmake ninja
    make --version
    cmake --version
    ninja --version
    # gdb cannot be installed by brew on macOS 14 with Apple Silicon chips as of 20240219
    (brew install gdb &> /dev/null && gbd --version) || echo "!!! WARNING: gdb cannot be installed !!!"
elif [[ "$RUNNER_OS" == "Windows" ]] ; then
    choco install wget make cmake ninja --no-progress  # gdb cannot be installed by choco
    make --version
    cmake --version
    ninja --version
fi
