#!/bin/bash
# This script installs miscellaneous applications for GitHub Actions on ***hosted runners***.
# Usage: bash mist_setup

# Exist if the runner is not hosted. Is there a better way to decide the runner type?
if [[ ("$RUNNER_OS" == "Linux" && ! -d /home/runner/work/) || ("$RUNNER_OS" == "macOS" && ! -d /Users/runner/work/) ]] ; then
    printf "\nThe runner is not hosted by GitHub.\n"
    exit 0
fi

if [[ "$RUNNER_OS" == "Linux" ]] ; then
    sudo apt update
    sudo apt install gdb make cmake ninja-build
    gdb --version
    make --version
    cmake --version
    ninja --version
elif [[ "$RUNNER_OS" == "macOS" ]] ; then
    brew install coreutils make cmake ninja
    make --version
    cmake --version
    ninja --version
    (brew install gdb && gbd --version) || :  # gdb cannot be installed by brew on macOS 14 with Apple Silicon chips as of 20240219
elif [[ "$RUNNER_OS" == "Windows" ]] ; then
    choco install wget make cmake ninja --no-progress  # gdb cannot be installed by choco
    make --version
    cmake --version
    ninja --version
fi
