#!/usr/bin/env bash
# This script sets the miscellanies environment variables and installs miscellaneous libraries
# for GitHub Actions.
#
# Usage: bash misc_setup

# The directory where this scrip resides
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

bash "$SCRIPT_DIR"/misc_env
bash "$SCRIPT_DIR"/misc_lib

# The following line resizes the swap of GitHub-hosted Linux runners.
# As of 20250727, this is needed by profiling PRIMA on MATLAB R2025a, or the GitHub-hosted runners
# may shut down due to memory starvation. This did not happen with earlier versions of MATLAB.
# For GITHUB_ACTIONS, RUNNER_ENVIRONMENT, and RUNNER_OS variables, see:
# https://docs.github.com/en/actions/reference/workflows-and-actions/variables
SWAP_SIZE=16
if [[ "$GITHUB_ACTIONS" == "true" && "$RUNNER_ENVIRONMENT" == "github-hosted" && "$RUNNER_OS" == "Linux" ]]; then
    bash "$SCRIPT_DIR"/resize_swap "$SWAP_SIZE"
fi

echo -e "\n*********************************************************************************************\n"
echo "System Information:"
if [[ "$RUNNER_OS" == "Linux" ]]; then
    lscpu
    lsmem
    df -h
elif [[ "$RUNNER_OS" == "macOS" ]]; then
    sysctl -a | grep machdep.cpu
    echo Total Memory: "$(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 ))" GB
    df -h
elif [[ "$RUNNER_OS" == "Windows" ]]; then
    systeminfo
    wmic logicaldisk get DeviceID,Size,FreeSpace
else
    echo "Unknown OS: $RUNNER_OS"
    exit 1
fi
echo -e "\n*********************************************************************************************\n"
